apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: flux-system
    namespace: flux-system
spec:
    interval: 1m0s
    url: https://github.com/iac-factory/cluster-management
    ref:
        branch: main
    secretRef:
        name: flux-system
