apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - installation.yaml
    - git-repository.yaml
    - external-secrets.yaml
    - kyverno.yaml
    - prometheus.yaml

secretGenerator:
    -   name: flux-system
        options:
            disableNameSuffixHash: true
        type: Opaque
        namespace: flux-system
        files:
            - .secrets/username
            - .secrets/password

    -   name: aws-provider-credentials
        options:
            disableNameSuffixHash: true
        type: Opaque
        namespace: flux-system
        files:
            - .secrets/aws-access-key-id
            - .secrets/aws-secret-access-key
