apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - installation.yaml
    - git-repository.yaml
    - external-secrets.yaml
    - kyverno.yaml
    - prometheus.yaml
    - crossplane.yaml

    - aws-crossplane-management-network.yaml
    - aws-crossplane-management-cluster.yaml

secretGenerator:
    -   name: flux-system
        options:
            disableNameSuffixHash: true
        type: Opaque
        namespace: flux-system
        files:
            - .secrets/username
            - .secrets/password

    -   name: aws-external-secrets-credentials
        options:
            disableNameSuffixHash: true
        type: Opaque
        namespace: flux-system
        files:
            - .secrets/aws-access-key-id
            - .secrets/aws-secret-access-key

    -   name: aws-crossplane-credentials
        options:
            disableNameSuffixHash: true
        type: Opaque
        namespace: flux-system
        files:
            - .secrets/profile
